language: c
addons:
  hosts:
    - haywire.test
install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq httperf
script:
  - ./build.sh
  - ./bin/wrk/wrk -d10 -t8 -c1024 --pipeline 64 --latency http://haywire.test
  - ./bin/wrk/wrk -d10 -t8 -c8 --pipeline 1024 --latency http://haywire.test
  - httperf --server=haywire.test --num-conns=8 --num-calls=10000
  - ab -n 100000 -c 32 -k http://haywire.test